#a=input("Enter something:")
#print("A:",type(a))
#b=int(input("Enter interger:"))
#print("B:",type(b))
#c=int(a)
#print("C:",type(c))
#d=eval(input("Enter new interger:"))
#print("D:",type(d),d)
#e=eval('10+5*2')
#print("E:",e)
print("ab" in "def")